pipeline {
    agent none
    options { skipDefaultCheckout(true) }
    stages {
        stage('Build and Test') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            options { skipDefaultCheckout(false) }
            steps {
                sh 'mvn -f BE/Dayugi/pom.xml -B -DskipTests clean package'
            }
        }
        stage('Docker build') {
            agent any
            steps {
                sh 'docker build -t java-migrator-image:latest ./BE/Dayugi'
            }
        }
        stage('Docker run') {
            agent any
            steps {
                sh 'docker ps -f name=java-migrator-container -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -fname=java-migrator-container -q | xargs -r docker container rm'
                sh 'docker run -d --name java-migrator-container -v /home/ubuntu/share/nginx/html/:/home/image -p 8080:8080 java-migrator-image:latest'
            }
        }
    }
}

